name: SayHello

on:
  push:
    branches:
      - develop
      - main

jobs:
  detect-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Download Source
        uses: actions/checkout@v4

      - name: Say Hello Main
        if: ${{ github.ref == 'refs/heads/main' }}
        run: echo "¡Hola, Main!"

      - name: Say Hello Develop
        if: ${{ github.ref == 'refs/heads/develop' }}
        run: echo "¡Hola, Developer!"
